"""add is_active to services

Revision ID: 813da45630e9
Revises: 0006_audit_logs
Create Date: 2026-09-11 05:48:14.684282
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '813da45630e9'
down_revision: Union[str, None] = '0006_audit_logs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'is_active')
    # ### end Alembic commands ###
