"""add whatsapp communication tables

Revision ID: d9d127aba918
Revises: 813da45630e9
Create Date: 2026-09-12 07:59:33.289665
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd9d127aba918'
down_revision: Union[str, None] = '813da45630e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('waba_id', sa.String(length=64), nullable=True),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('display_phone_number', sa.String(length=32), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_channels_clinic_id'), 'whatsapp_channels', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_channels_phone_number_id'), 'whatsapp_channels', ['phone_number_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('whatsapp_channel_id', sa.Integer(), nullable=False),
    sa.Column('wa_contact_id', sa.String(length=64), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['whatsapp_channel_id'], ['whatsapp_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_channel_id', 'wa_contact_id', name='uq_conversation_channel_contact')
    )
    op.create_index(op.f('ix_conversations_clinic_id'), 'conversations', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_conversations_patient_id'), 'conversations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_conversations_whatsapp_channel_id'), 'conversations', ['whatsapp_channel_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('message_type', sa.String(length=30), server_default='text', nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_clinic_id'), 'messages', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_provider_message_id'), 'messages', ['provider_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_provider_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_clinic_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_whatsapp_channel_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_patient_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_clinic_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_whatsapp_channels_phone_number_id'), table_name='whatsapp_channels')
    op.drop_index(op.f('ix_whatsapp_channels_clinic_id'), table_name='whatsapp_channels')
    op.drop_table('whatsapp_channels')
    # ### end Alembic commands ###
